// Generated by CoffeeScript 1.6.3
(function() {
  var app, aws, config, express, http, nconf, path, sqs, twilio;

  express = require('express');

  http = require('http');

  path = require('path');

  twilio = require('twilio');

  nconf = require('nconf');

  aws = require('aws-sdk');

  app = express();

  app.set('port', process.env.PORT || 3000);

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  nconf.argv().env().file('config.json');

  config = {};

  config.twilio = {};

  config.twilio.accountSid = nconf.get('TWILIO_ACCOUNT_SID');

  config.twilio.authToken = nconf.get('TWILIO_AUTH_TOKEN');

  config.sqs = {};

  config.sqs.apiVersion = nconf.get('AWS_API_VERSION');

  config.sqs.accessKeyId = nconf.get('AWS_ACCESS_KEY_ID');

  config.sqs.secretAccessKey = nconf.get('AWS_ACCESS_KEY_SECRET');

  config.sqs.endpoint = nconf.get('AWS_ENDPOINT_URL');

  config.sqs.region = nconf.get('AWS_REGION');

  sqs = new aws.SQS(config.sqs);

  app.post('/twiml', function(res, req) {
    var message;
    if (req.headers == null) {
      req.headers = {};
    }
    req.headers.host = req.host;
    if (twilio.validateExpressRequest(req, config.twilio.authToken)) {
      message = {};
      message.QueueUrl = config.sqs.endpoint;
      message.MessageBody = req.body.body + '[' + req.body.from + ']';
      sqs.sendMessage(message, function(err, data) {
        if (err != null) {
          return console.log(err);
        }
      });
      return res.send(200);
    } else {
      return res.send(403);
    }
  });

  (http.createServer(app)).listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

}).call(this);
